export const light = {
  color: {
    background: "#fbfbfb",
    button: "#c6e7ff",
    buttonBackground: "#00aaff",
    buttonFont: "#ffffff",
    cardDark: "#cbcbce",
    cardLight: "#ffffff",
    cardFont: "#292f33",
    orange: "#ffddae",
    border: "#35374b",
    cardShadow: "#44444444",
    cardShadowHover: "#4444443a",
    fontOnBackground: "#004488",
    paginationBackground: "#ffffff44",
    paginationButton: "#ff0000",
    fightButton: "#ff3300",
    fightButtonInactive: "#aaaaaa",
    fightButtonInactiveFont: "#eeeeee",
    fightButtonPressed: "#ee0000",
    tableSecondaryColor: "#aaeeff",
    tableSecondaryFontColor: "#004488",
    errorMessage: "#ff0000",
    inputBorder: "#aaaaaa",
    inputBorderFocus: "#888888",
    modalShadow: "#444444",
  },
};

export const dark = {
  color: {
    background: "#35374b",
    button: "#c6e7ff",
    buttonBackground: "#00aaff",
    buttonFont: "#ffffff",
    cardDark: "#888888",
    cardLight: "#ffffff",
    cardFont: "#292f33",
    orange: "#ffddae",
    border: "#fbfbfb",
    cardShadow: "#bbbbbb44",
    fontOnBackground: "#ffffff",
    paginationBackground: "#00000077",
    paginationButton: "#ff0000",
    fightButton: "#ff3300",
    fightButtonInactive: "#cccccc",
    fightButtonInactiveFont: "#eeeeee",
    fightButtonPressed: "#ee0000",
    tableSecondaryColor: "#aaeeff",
    tableSecondaryFontColor: "#35374b",
    errorMessage: "#ff0000",
    inputBorder: "#aaaaaa",
    inputBorderFocus: "#888888",
  },
};
